### ISSUE TITLE
Bug: License agreement needed for MLPro Extension Hub

### ISSUE THREAD

**Issue by detlefarend** [fhswf/mt_baheti#1]
**1 Describe the bug**
This repo is labelled as MLPro extension. To be listed in the extension hub a license agreement is necessary.

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , an MIT license will be fine, right?

**Comment by detlefarend** [comment]
> Hi @detlefarend , an MIT license will be fine, right?

MIT or Apache 2.0. In MLPro we chose the latter one.

**Comment by laxmikantbaheti** [comment]
And the copyright info here should include name of the organisation, that is university? Or me? Since it's hosted on the organisation. In mlpro it's university.

**Comment by detlefarend** [comment]
It's your work. The copyright is yours.

**Comment by laxmikantbaheti** [comment]
> It's your work. The copyright is yours.

Done.
